'use strict';

const { Family, Confidence, RightsStatus, AIProvenance, EvidenceStatus, EvidenceSource } = require('./schema');

/**
 * Evidence rules. Every match carries a confidence and its evidence SOURCE, and
 * the different evidence kinds are never conflated (a Suno CDN string is
 * provenance evidence, NOT an invisible-watermark detection).
 */

// pattern families. `bareAI` marks the 2-letter "ai" coincidence that must stay LOW.
const PATTERNS = [
  { family: Family.SUNO, re: /cdn[0-9]?\.suno\.ai/i, base: Confidence.MEDIUM },
  { family: Family.SUNO, re: /cdn-o\.suno\.com/i, base: Confidence.MEDIUM },
  { family: Family.SUNO, re: /suno\.ai/i, base: Confidence.MEDIUM },
  { family: Family.SUNO, re: /suno\.com/i, base: Confidence.MEDIUM },
  { family: Family.SUNO, re: /\bsuno\b/i, base: Confidence.MEDIUM },
  { family: Family.AI, re: /\bai[\s-]?generated\b/i, base: Confidence.MEDIUM },
  { family: Family.AI, re: /artificial intelligence/i, base: Confidence.MEDIUM },
  { family: Family.AI, re: /machine[\s-]?generated/i, base: Confidence.MEDIUM },
  { family: Family.AI, re: /model[\s-]?generated/i, base: Confidence.MEDIUM },
  { family: Family.AI, re: /\bgenerative\b/i, base: Confidence.MEDIUM },
  { family: Family.AI, re: /\bsynthetic\b/i, base: Confidence.LOW },
  { family: Family.AI, re: /\bai\b/i, base: Confidence.LOW, bareAI: true },
  { family: Family.MODEL, re: /generated by/i, base: Confidence.MEDIUM },
  { family: Family.MODEL, re: /created (?:with|using)/i, base: Confidence.MEDIUM },
  { family: Family.MODEL, re: /\bgenerator\b/i, base: Confidence.LOW },
  { family: Family.RIGHTS, re: /non[\s-]?commercial/i, base: Confidence.MEDIUM, rights: 'noncommercial' },
  { family: Family.RIGHTS, re: /personal use only/i, base: Confidence.MEDIUM, rights: 'noncommercial' },
  { family: Family.RIGHTS, re: /commercial use/i, base: Confidence.MEDIUM, rights: 'commercial' },
  { family: Family.RIGHTS, re: /royalty[\s-]?free/i, base: Confidence.MEDIUM, rights: 'commercial' },
  { family: Family.RIGHTS, re: /\bcommercial\b/i, base: Confidence.LOW, rights: 'commercial' },
  { family: Family.RIGHTS, re: /rights reserved/i, base: Confidence.MEDIUM, rights: 'copyright' },
  { family: Family.RIGHTS, re: /\bcopyright\b/i, base: Confidence.LOW, rights: 'copyright' },
  { family: Family.RIGHTS, re: /\blicen[sc]e\b/i, base: Confidence.LOW, rights: 'license' },
  { family: Family.PROVENANCE, re: /watermark/i, base: Confidence.LOW },
  { family: Family.PROVENANCE, re: /fingerprint/i, base: Confidence.LOW },
  { family: Family.PROVENANCE, re: /provenance/i, base: Confidence.LOW },
];

const STRONG_STRUCT_KEY = /(encoder|encoded_by|software|generator|provider|vendor|tool|source|comment|copyright|artist|album|title|description)/i;

function elevate(conf) {
  if (conf === Confidence.LOW) return Confidence.MEDIUM;
  if (conf === Confidence.MEDIUM) return Confidence.HIGH;
  return Confidence.HIGH;
}

function excerpt(text) {
  return String(text).replace(/\s+/g, ' ').trim().slice(0, 120);
}

/**
 * Classify a single text value against the keyword families.
 * @param {string} text
 * @param {{structured?:boolean, key?:string, source?:string}} opts
 */
function classifyText(text, opts = {}) {
  const out = [];
  if (!text) return out;
  for (const p of PATTERNS) {
    if (!p.re.test(text)) continue;
    let confidence = p.base;
    // Structured metadata in a meaningful field is stronger — but a bare "ai"
    // coincidence never gets promoted.
    if (opts.structured && !p.bareAI && STRONG_STRUCT_KEY.test(opts.key || '')) {
      confidence = elevate(confidence);
    }
    out.push({
      family: p.family,
      pattern: p.re.source,
      confidence,
      bareAI: !!p.bareAI,
      rights: p.rights || null,
      source: opts.source || (opts.structured ? EvidenceSource.FILE_METADATA : EvidenceSource.RAW_STRING),
      key: opts.key || null,
      text: excerpt(text),
    });
  }
  return out;
}

/**
 * Rights / commercial-use evaluation. The file alone can never CONFIRM a
 * commercial license, so the strongest non-conflicting outcome is UNKNOWN.
 */
function analyzeRights(evidence) {
  const rights = evidence.filter((e) => e.family === Family.RIGHTS && e.rights);
  const hasCommercial = rights.some((e) => e.rights === 'commercial');
  const hasNoncommercial = rights.some((e) => e.rights === 'noncommercial');
  let status = RightsStatus.UNKNOWN;
  if (hasCommercial && hasNoncommercial) status = RightsStatus.CONFLICTING_EVIDENCE;
  return {
    status,
    evidence: rights.map((e) => ({ kind: e.rights, confidence: e.confidence, source: e.source, key: e.key, text: e.text })),
    limitations: [
      'A commercial license cannot be confirmed from the audio file alone. File metadata is not a machine-verifiable license grant.',
    ],
  };
}

/** Aggregate provenance evidence into an AI_PROVENANCE classification. */
function aggregateProvenance(evidence, sourceProvenance) {
  const weight = { HIGH: 3, MEDIUM: 2, LOW: 1 };
  let score = 0;
  const counted = [];
  for (const e of evidence) {
    if (e.family === Family.RIGHTS) continue; // rights handled separately
    if (e.bareAI) {
      counted.push({ ...e, weighted: 0 });
      continue; // noise: recorded but never scored
    }
    const w = weight[e.confidence] || 0;
    score += w;
    counted.push({ ...e, weighted: w });
  }
  const hasSource = !!sourceProvenance;
  if (hasSource) score += 2; // known import source is corroborating evidence

  let classification;
  if (score >= 6) classification = AIProvenance.STRONG_EVIDENCE;
  else if (score >= 3) classification = AIProvenance.MODERATE_EVIDENCE;
  else if (score >= 1) classification = AIProvenance.WEAK_EVIDENCE;
  else classification = AIProvenance.NO_EVIDENCE_FOUND;

  return {
    classification,
    score,
    sourceProvenance: sourceProvenance || null,
    evidence: counted.map((e) => ({ family: e.family, confidence: e.confidence, source: e.source, key: e.key, text: e.text, bareAI: e.bareAI })),
    notes: [
      'This aggregates provenance evidence only; it is NOT a probability and NOT a legal determination of authorship.',
    ],
  };
}

/**
 * Watermark detector registry. There is NO verified public detector for a
 * proprietary invisible audio watermark, so the overall status stays UNKNOWN.
 * Metadata/string findings are reported as provenance, never as a watermark.
 */
function runWatermarkRegistry(ctx) {
  const detectors = [];

  detectors.push({
    id: 'suno-invisible-watermark',
    name: 'Suno invisible audio watermark',
    version: '1.0.0',
    provider: 'none',
    evidenceType: 'audio-signal',
    status: EvidenceStatus.UNSUPPORTED,
    confidence: null,
    findings: [],
    limitations: [
      'No public, verifiable specification or detector for a proprietary Suno invisible watermark is available in this build. Presence or absence CANNOT be determined from the file.',
    ],
  });

  const vendorHits = (ctx.provenanceEvidence || []).filter(
    (e) => e.family === Family.SUNO || e.family === Family.PROVENANCE
  );
  detectors.push({
    id: 'vendor-string',
    name: 'Vendor / provenance string detector',
    version: '1.0.0',
    provider: 'local',
    evidenceType: 'metadata+string',
    status: vendorHits.length ? EvidenceStatus.DETECTED : EvidenceStatus.NOT_DETECTED,
    confidence: vendorHits.some((e) => e.confidence === Confidence.HIGH) ? Confidence.HIGH : vendorHits.length ? Confidence.MEDIUM : null,
    findings: vendorHits.slice(0, 20).map((e) => ({ family: e.family, confidence: e.confidence, source: e.source, text: e.text })),
    limitations: ['Reports provenance evidence only. This is NOT proof of an embedded invisible watermark.'],
  });

  const privateCount = ctx.privateDataCount || 0;
  detectors.push({
    id: 'container-private-field',
    name: 'Container private/unknown data detector',
    version: '1.0.0',
    provider: 'local',
    evidenceType: 'container',
    status: privateCount > 0 ? EvidenceStatus.DETECTED : EvidenceStatus.NOT_DETECTED,
    confidence: privateCount > 0 ? Confidence.LOW : null,
    findings: [{ unknownOrPrivateBlocks: privateCount }],
    limitations: [
      'Unknown/private container data is reported as-is. Its presence is NOT evidence of a watermark.',
    ],
  });

  return {
    status: EvidenceStatus.UNKNOWN, // no verified detector can prove/disprove it
    detectors,
    limitations: [
      'Invisible-watermark presence is UNKNOWN: no verified detector exists here. NOT_DETECTED by metadata/string scans does NOT mean a watermark is absent.',
    ],
  };
}

module.exports = { classifyText, analyzeRights, aggregateProvenance, runWatermarkRegistry, PATTERNS };
